set SRCPATH=%~dp0
cd "%SRCPATH%CFG\"

rem NOTE - DO NOT EDIT THOSE AUTOGENERATED FILES!


rem --- LINUX

copy /B "Base\TgtLinX86X32.txt" + "Base\Base.cfg" + "Base\BaseDbg.cfg" + "Base\BaseLinUsr.cfg" + "Base\BaseX86.cfg" "DBG_LIN_USR_X86_X32.cfg"
copy /B "Base\TgtLinX86X32.txt" + "Base\Base.cfg" + "Base\BaseRel.cfg" + "Base\BaseLinUsr.cfg" + "Base\BaseX86.cfg" "REL_LIN_USR_X86_X32.cfg"

copy /B "Base\TgtLinX86X64.txt" + "Base\Base.cfg" + "Base\BaseDbg.cfg" + "Base\BaseLinUsr.cfg" + "Base\BaseX86.cfg" "DBG_LIN_USR_X86_X64.cfg"
copy /B "Base\TgtLinX86X64.txt" + "Base\Base.cfg" + "Base\BaseRel.cfg" + "Base\BaseLinUsr.cfg" + "Base\BaseX86.cfg" "REL_LIN_USR_X86_X64.cfg"


copy /B "Base\TgtLinArm32.txt" + "Base\Base.cfg" + "Base\BaseDbg.cfg" + "Base\BaseLinUsr.cfg" + "Base\BaseARM.cfg" + "Base\BaseARM32.cfg" "DBG_LIN_USR_ARM_X32.cfg"
copy /B "Base\TgtLinArm32.txt" + "Base\Base.cfg" + "Base\BaseRel.cfg" + "Base\BaseLinUsr.cfg" + "Base\BaseARM.cfg" + "Base\BaseARM32.cfg" "REL_LIN_USR_ARM_X32.cfg"

copy /B "Base\TgtLinArm64.txt" + "Base\Base.cfg" + "Base\BaseDbg.cfg" + "Base\BaseLinUsr.cfg" + "Base\BaseARM.cfg" + "Base\BaseARM64.cfg" "DBG_LIN_USR_ARM_X64.cfg"
copy /B "Base\TgtLinArm64.txt" + "Base\Base.cfg" + "Base\BaseRel.cfg" + "Base\BaseLinUsr.cfg" + "Base\BaseARM.cfg" + "Base\BaseARM64.cfg" "REL_LIN_USR_ARM_X64.cfg"


copy /B "Base\Base.cfg" + "Base\BaseDbg.cfg" + "Base\BaseLinUsr.cfg" + "Base\BaseARM.cfg" + "Base\BaseARM32.cfg" + "Base\BaseOldARM.cfg" "DBG_LIN_USR_OARM_X32.cfg"
copy /B "Base\Base.cfg" + "Base\BaseRel.cfg" + "Base\BaseLinUsr.cfg" + "Base\BaseARM.cfg" + "Base\BaseARM32.cfg" + "Base\BaseOldARM.cfg" "REL_LIN_USR_OARM_X32.cfg"



rem --- WINDOWS (TODO - ARM)

copy /B "Base\TgtWinX86X32.txt" + "Base\Base.cfg" + "Base\BaseDbg.cfg" + "Base\BaseWinUsr.cfg" + "Base\BaseX86.cfg" "DBG_WIN_USR_X86_X32.cfg"
copy /B "Base\TgtWinX86X32.txt" + "Base\Base.cfg" + "Base\BaseRel.cfg" + "Base\BaseWinUsr.cfg" + "Base\BaseX86.cfg" "REL_WIN_USR_X86_X32.cfg"

copy /B "Base\TgtWinX86X64.txt" + "Base\Base.cfg" + "Base\BaseDbg.cfg" + "Base\BaseWinUsr.cfg" + "Base\BaseX86.cfg" "DBG_WIN_USR_X86_X64.cfg"
copy /B "Base\TgtWinX86X64.txt" + "Base\Base.cfg" + "Base\BaseRel.cfg" + "Base\BaseWinUsr.cfg" + "Base\BaseX86.cfg" "REL_WIN_USR_X86_X64.cfg"



rem --- MacOS (TODO - ARM)

copy /B "Base\TgtMacX86X64.txt" + "Base\Base.cfg" + "Base\BaseDbg.cfg" + "Base\BaseMacUsr.cfg" + "Base\BaseX86.cfg" "DBG_MAC_USR_EXE_X86_X64.cfg"
copy /B "Base\TgtMacX86X64.txt" + "Base\Base.cfg" + "Base\BaseRel.cfg" + "Base\BaseMacUsr.cfg" + "Base\BaseX86.cfg" "REL_MAC_USR_EXE_X86_X64.cfg"

copy /B "Base\TgtMacX86X64.txt" + "Base\Base.cfg" + "Base\BaseDbg.cfg" + "Base\BaseMacUsr.cfg" + "Base\BaseX86.cfg" "DBG_MAC_USR_DLL_X86_X64.cfg"
copy /B "Base\TgtMacX86X64.txt" + "Base\Base.cfg" + "Base\BaseRel.cfg" + "Base\BaseMacUsr.cfg" + "Base\BaseX86.cfg" "REL_MAC_USR_DLL_X86_X64.cfg"



rem --- BSD

copy /B "Base\TgtBsdX86X32.txt" + "Base\Base.cfg" + "Base\BaseDbg.cfg" + "Base\BaseBsdUsr.cfg" + "Base\BaseX86.cfg" "DBG_BSD_USR_X86_X32.cfg"
copy /B "Base\TgtBsdX86X32.txt" + "Base\Base.cfg" + "Base\BaseRel.cfg" + "Base\BaseBsdUsr.cfg" + "Base\BaseX86.cfg" "REL_BSD_USR_X86_X32.cfg"

copy /B "Base\TgtBsdX86X64.txt" + "Base\Base.cfg" + "Base\BaseDbg.cfg" + "Base\BaseBsdUsr.cfg" + "Base\BaseX86.cfg" "DBG_BSD_USR_X86_X64.cfg"
copy /B "Base\TgtBsdX86X64.txt" + "Base\Base.cfg" + "Base\BaseRel.cfg" + "Base\BaseBsdUsr.cfg" + "Base\BaseX86.cfg" "REL_BSD_USR_X86_X64.cfg"


copy /B "Base\TgtBsdArm32.txt" + "Base\Base.cfg" + "Base\BaseDbg.cfg" + "Base\BaseBsdUsr.cfg" + "Base\BaseARM.cfg" + "Base\BaseARM32.cfg" "DBG_BSD_USR_ARM_X32.cfg"
copy /B "Base\TgtBsdArm32.txt" + "Base\Base.cfg" + "Base\BaseRel.cfg" + "Base\BaseBsdUsr.cfg" + "Base\BaseARM.cfg" + "Base\BaseARM32.cfg" "REL_BSD_USR_ARM_X32.cfg"

copy /B "Base\TgtBsdArm64.txt" + "Base\Base.cfg" + "Base\BaseDbg.cfg" + "Base\BaseBsdUsr.cfg" + "Base\BaseARM.cfg" + "Base\BaseARM64.cfg" "DBG_BSD_USR_ARM_X64.cfg"
copy /B "Base\TgtBsdArm64.txt" + "Base\Base.cfg" + "Base\BaseRel.cfg" + "Base\BaseBsdUsr.cfg" + "Base\BaseARM.cfg" + "Base\BaseARM64.cfg" "REL_BSD_USR_ARM_X64.cfg"



rem --- UBOOT

copy /B "Base\TgtLinArm32.txt" + "Base\Base.cfg" + "Base\BaseDbg.cfg" + "Base\BaseUBoot.cfg" + "Base\BaseARM.cfg" + "Base\BaseARM32.cfg" "DBG_UBT_ARM_X32.cfg"
copy /B "Base\TgtLinArm32.txt" + "Base\Base.cfg" + "Base\BaseRel.cfg" + "Base\BaseUBoot.cfg" + "Base\BaseARM.cfg" + "Base\BaseARM32.cfg" "REL_UBT_ARM_X32.cfg"

copy /B "Base\TgtLinArm64.txt" + "Base\Base.cfg" + "Base\BaseDbg.cfg" + "Base\BaseUBoot.cfg" + "Base\BaseARM.cfg" + "Base\BaseARM64.cfg" "DBG_UBT_ARM_X64.cfg"
copy /B "Base\TgtLinArm64.txt" + "Base\Base.cfg" + "Base\BaseRel.cfg" + "Base\BaseUBoot.cfg" + "Base\BaseARM.cfg" + "Base\BaseARM64.cfg" "REL_UBT_ARM_X64.cfg"

copy /B "Base\Base.cfg" + "Base\BaseDbg.cfg" + "Base\BaseUBoot.cfg" + "Base\BaseARM.cfg" + "Base\BaseARM32.cfg" + "Base\BaseOldARM.cfg" "DBG_OUBT_ARM_X32.cfg"
copy /B "Base\Base.cfg" + "Base\BaseRel.cfg" + "Base\BaseUBoot.cfg" + "Base\BaseARM.cfg" + "Base\BaseARM32.cfg" + "Base\BaseOldARM.cfg" "REL_OUBT_ARM_X32.cfg"



rem --- RAW BIN

copy /B "Base\TgtLinX86X32.txt" + "Base\Base.cfg" + "Base\BaseDbg.cfg" + "Base\BaseX86.cfg" + "Base\BaseRaw.cfg" "DBG_RAW_X86_X32.cfg"
copy /B "Base\TgtLinX86X32.txt" + "Base\Base.cfg" + "Base\BaseRel.cfg" + "Base\BaseX86.cfg" + "Base\BaseRaw.cfg" "REL_RAW_X86_X32.cfg"

copy /B "Base\TgtLinX86X64.txt" + "Base\Base.cfg" + "Base\BaseDbg.cfg" + "Base\BaseX86.cfg" + "Base\BaseRaw.cfg" "DBG_RAW_X86_X64.cfg"
copy /B "Base\TgtLinX86X64.txt" + "Base\Base.cfg" + "Base\BaseRel.cfg" + "Base\BaseX86.cfg" + "Base\BaseRaw.cfg" "REL_RAW_X86_X64.cfg"


copy /B "Base\TgtLinArm32.txt" + "Base\Base.cfg" + "Base\BaseDbg.cfg" + "Base\BaseARM.cfg" + "Base\BaseARM32.cfg" + "Base\BaseRaw.cfg" "DBG_RAW_ARM_X32.cfg"
copy /B "Base\TgtLinArm32.txt" + "Base\Base.cfg" + "Base\BaseRel.cfg" + "Base\BaseARM.cfg" + "Base\BaseARM32.cfg" + "Base\BaseRaw.cfg" "REL_RAW_ARM_X32.cfg"

copy /B "Base\TgtLinArm64.txt" + "Base\Base.cfg" + "Base\BaseDbg.cfg" + "Base\BaseARM.cfg" + "Base\BaseARM64.cfg" + "Base\BaseRaw.cfg" "DBG_RAW_ARM_X64.cfg"
copy /B "Base\TgtLinArm64.txt" + "Base\Base.cfg" + "Base\BaseRel.cfg" + "Base\BaseARM.cfg" + "Base\BaseARM64.cfg" + "Base\BaseRaw.cfg" "REL_RAW_ARM_X64.cfg"


copy /B "Base\Base.cfg" + "Base\BaseDbg.cfg" + "Base\BaseARM.cfg" + "Base\BaseARM32.cfg" + "Base\BaseOldARM.cfg" + "Base\BaseRaw.cfg" "DBG_RAW_OARM_X32.cfg"
copy /B "Base\Base.cfg" + "Base\BaseRel.cfg" + "Base\BaseARM.cfg" + "Base\BaseARM32.cfg" + "Base\BaseOldARM.cfg" + "Base\BaseRaw.cfg" "REL_RAW_OARM_X32.cfg"



pause